import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Clock3, Flame, Loader2 } from "lucide-react";
import { supabase } from "../lib/supabase";

type Period = "week" | "month" | "year";
type AttendanceRow = { session_id: string; joined_at: string | null; left_at: string | null; last_seen_at: string | null; created_at: string | null };
type DailyAttendanceRow = { session_id: string; attendance_date: string };
type CompletedTaskRow = { id: string; text: string | null; target_date?: string | null; created_at: string | null };
type ProgressEvent = { key: string; date: string; minutes: number };
const PERIOD_DAYS: Record<Period, number> = { week: 7, month: 30, year: 365 };

function dateKey(value: string | Date | null | undefined, timeZone: string) {
  if (!value) return "";
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date);
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value || "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}
function addDays(date: Date, days: number) { const next = new Date(date); next.setDate(next.getDate() + days); return next; }
function formatDuration(totalMinutes: number) { const minutes = Math.max(0, Math.round(totalMinutes)); if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); const rest = minutes % 60; return rest ? `${hours}h ${rest}m` : `${hours}h`; }
function getAttendanceMinutes(row: AttendanceRow) { const start = new Date(row.joined_at || row.created_at || "").getTime(); const end = new Date(row.left_at || row.last_seen_at || "").getTime(); if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) return 0; return Math.min(12 * 60, Math.max(0, (end - start) / 60_000)); }
function getStreak(activeDates: Set<string>, timeZone: string) { let cursor = new Date(); let streak = 0; let key = dateKey(cursor, timeZone); if (!activeDates.has(key)) { cursor = addDays(cursor, -1); key = dateKey(cursor, timeZone); } while (key && activeDates.has(key)) { streak += 1; cursor = addDays(cursor, -1); key = dateKey(cursor, timeZone); } return streak; }

export default function ProfileProgressDashboard({ userId, timeZone }: { userId: string; timeZone: string }) {
  const [period, setPeriod] = useState<Period>("month");
  const [attendance, setAttendance] = useState<AttendanceRow[]>([]);
  const [dailyAttendance, setDailyAttendance] = useState<DailyAttendanceRow[]>([]);
  const [tasks, setTasks] = useState<CompletedTaskRow[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; setLoading(true); void Promise.all([
    supabase.from("session_attendance").select("session_id, joined_at, left_at, last_seen_at, created_at").eq("user_id", userId).order("joined_at", { ascending: false }).limit(1000),
    supabase.from("infinite_room_daily_attendance").select("session_id, attendance_date").eq("user_id", userId).order("attendance_date", { ascending: false }).limit(1500),
    supabase.from("focus_plan_items").select("id, text, target_date, created_at").eq("user_id", userId).eq("completed", true).order("created_at", { ascending: false }).limit(500),
    supabase.from("intentions").select("id, text, created_at").eq("user_id", userId).eq("completed", true).order("created_at", { ascending: false }).limit(500),
  ]).then(([attendanceResult, dailyResult, planResult, intentionsResult]) => { if (cancelled) return; setAttendance(attendanceResult.error ? [] : (attendanceResult.data as AttendanceRow[]) || []); setDailyAttendance(dailyResult.error ? [] : (dailyResult.data as DailyAttendanceRow[]) || []); const planRows = ((planResult.error ? [] : planResult.data) || []) as CompletedTaskRow[]; const intentionRows = ((intentionsResult.error ? [] : intentionsResult.data) || []) as CompletedTaskRow[]; const combined = [...planRows.map((row) => ({ ...row, id: `plan:${row.id}` })), ...intentionRows.map((row) => ({ ...row, id: `intention:${row.id}` }))]; setTasks(combined.sort((a, b) => new Date(b.created_at || 0).getTime() - new Date(a.created_at || 0).getTime())); }).catch((error) => { console.warn("[profile-progress] load failed", error); if (!cancelled) { setAttendance([]); setDailyAttendance([]); setTasks([]); } }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [userId]);
  const events = useMemo(() => { const result = new Map<string, ProgressEvent>(); attendance.forEach((row) => { const date = dateKey(row.joined_at || row.created_at, timeZone); if (!date || !row.session_id) return; const key = `${row.session_id}:${date}`; result.set(key, { key, date, minutes: getAttendanceMinutes(row) }); }); dailyAttendance.forEach((row) => { const date = dateKey(row.attendance_date, timeZone); const key = `${row.session_id}:${date}`; if (date && !result.has(key)) result.set(key, { key, date, minutes: 0 }); }); return Array.from(result.values()).sort((a, b) => b.date.localeCompare(a.date)); }, [attendance, dailyAttendance, timeZone]);
  const periodStats = useMemo(() => { const start = dateKey(addDays(new Date(), -(PERIOD_DAYS[period] - 1)), timeZone); const filteredEvents = events.filter((event) => event.date >= start); const filteredTasks = tasks.filter((task) => dateKey(task.target_date || task.created_at, timeZone) >= start); const activeDates = new Set(events.map((event) => event.date)); return { sessions: filteredEvents.length, minutes: filteredEvents.reduce((sum, event) => sum + event.minutes, 0), tasks: filteredTasks.length, streak: getStreak(activeDates, timeZone) }; }, [events, period, tasks, timeZone]);
  return <section id="profile-progress" className="mt-8 scroll-mt-24 overflow-hidden rounded-[22px] bg-white ring-1 ring-black/[0.08]"><header className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="flex items-center gap-2"><CalendarDays size={17} className="text-[#2F2F2F]" /><div><h2 className="text-[17px] font-bold text-[#2F2F2F]">Your progress</h2><p className="text-[11px] text-[#858585]">Focused time and completed work.</p></div></div><div className="flex w-fit rounded-full bg-[#F1F1EF] p-1">{(["week", "month", "year"] as Period[]).map((item) => <button key={item} type="button" onClick={() => setPeriod(item)} className={`rounded-full px-3 py-1.5 text-[11px] font-semibold capitalize transition ${period === item ? "bg-[#2F2F2F] text-white" : "text-[#777] hover:text-[#2F2F2F]"}`}>{item}</button>)}</div></header>
    {loading ? <div className="grid min-h-32 place-items-center border-t border-black/[0.06]"><Loader2 className="animate-spin text-[#777]" size={21} /></div> : <div className="border-t border-black/[0.06] bg-[#FAFAF8] p-3 sm:p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[{ label: "Focused", value: formatDuration(periodStats.minutes), icon: <Clock3 size={14} /> }, { label: "Sessions", value: periodStats.sessions, icon: <CalendarDays size={14} /> }, { label: "Tasks", value: periodStats.tasks, icon: <Check size={14} /> }, { label: "Streak", value: `${periodStats.streak}d`, icon: <Flame size={14} /> }].map((stat) => <div key={stat.label} className="rounded-[14px] bg-white px-3 py-3"><div className="flex items-center gap-1.5 text-[10px] font-medium text-[#8A8A8A]">{stat.icon}{stat.label}</div><div className="mt-1.5 text-[20px] font-bold leading-none text-[#2F2F2F]">{stat.value}</div></div>)}</div><section className="mt-2 rounded-[14px] bg-white px-3 py-3"><div className="flex items-center justify-between gap-3"><h3 className="text-[12px] font-semibold text-[#2F2F2F]">Recently completed</h3><span className="text-[10px] font-medium text-[#999]">{tasks.length} total</span></div><div className="mt-2 grid gap-1 sm:grid-cols-2">{tasks.length ? tasks.slice(0, 4).map((task) => <div key={task.id} className="flex min-w-0 items-center gap-2 rounded-[10px] bg-[#F7F7F5] px-2.5 py-2"><span className="grid h-4 w-4 shrink-0 place-items-center rounded-full bg-[#D8F7DE] text-[#25843A]"><Check size={10} strokeWidth={3} /></span><p className="min-w-0 flex-1 truncate text-[11px] text-[#444]">{task.text || "Completed task"}</p><span className="shrink-0 text-[9px] text-[#A0A0A0]">{dateKey(task.target_date || task.created_at, timeZone)}</span></div>) : <div className="col-span-full py-3 text-center text-[11px] text-[#8C8C8C]">Completed tasks will appear here.</div>}</div></section></div>}
  </section>;
}
