import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Flame, Loader2 } from "lucide-react";
import { supabase } from "../lib/supabase";

type Period = "week" | "month" | "year";
type AttendanceRow = { session_id: string; joined_at: string | null; left_at: string | null; last_seen_at: string | null; created_at: string | null };
type DailyAttendanceRow = { session_id: string; attendance_date: string };
type CompletedTaskRow = { id: string; text: string | null; target_date?: string | null; created_at: string | null };
type ProgressEvent = { key: string; date: string; minutes: number };
const PERIOD_DAYS: Record<Period, number> = { week: 7, month: 30, year: 365 };

function dateKey(value: string | Date | null | undefined, timeZone: string) {
  if (!value) return "";
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date);
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value || "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}
function addDays(date: Date, days: number) { const next = new Date(date); next.setDate(next.getDate() + days); return next; }
function calendarDateKey(date: Date) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, "0"); const day = String(date.getDate()).padStart(2, "0"); return `${year}-${month}-${day}`; }
function formatDuration(totalMinutes: number) { const minutes = Math.max(0, Math.round(totalMinutes)); if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); const rest = minutes % 60; return rest ? `${hours}h ${rest}m` : `${hours}h`; }
function getAttendanceMinutes(row: AttendanceRow) { const start = new Date(row.joined_at || row.created_at || "").getTime(); const end = new Date(row.left_at || row.last_seen_at || "").getTime(); if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) return 0; return Math.min(12 * 60, Math.max(0, (end - start) / 60_000)); }
function getStreak(activeDates: Set<string>, timeZone: string) { let cursor = new Date(); let streak = 0; let key = dateKey(cursor, timeZone); if (!activeDates.has(key)) { cursor = addDays(cursor, -1); key = dateKey(cursor, timeZone); } while (key && activeDates.has(key)) { streak += 1; cursor = addDays(cursor, -1); key = dateKey(cursor, timeZone); } return streak; }

function Calendar({ events, timeZone }: { events: ProgressEvent[]; timeZone: string }) {
  const [cursor, setCursor] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const activity = useMemo(() => { const result = new Map<string, number>(); events.forEach((event) => result.set(event.date, (result.get(event.date) || 0) + 1)); return result; }, [events]);
  const cells = useMemo(() => { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const gridStart = addDays(first, -((first.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => addDays(gridStart, index)); }, [cursor]);
  const monthLabel = new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" }).format(cursor);
  const today = dateKey(new Date(), timeZone);
  return <section className="rounded-[22px] bg-[#F7F7F5] p-4 sm:p-5">
    <div className="mb-4 flex items-center justify-between gap-3"><div><h3 className="text-[15px] font-semibold text-[#2F2F2F]">Attendance calendar</h3><p className="mt-0.5 text-[11px] text-[#858585]">Every marked day is a day you showed up.</p></div><div className="flex items-center gap-1 rounded-full bg-white p-1"><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))} className="grid h-8 w-8 place-items-center rounded-full text-[#666] hover:bg-[#F0F0EE]" aria-label="Previous month"><ChevronLeft size={16} /></button><span className="min-w-[118px] text-center text-[12px] font-semibold text-[#2F2F2F]">{monthLabel}</span><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))} className="grid h-8 w-8 place-items-center rounded-full text-[#666] hover:bg-[#F0F0EE]" aria-label="Next month"><ChevronRight size={16} /></button></div></div>
    <div className="grid grid-cols-7 gap-1.5 text-center text-[10px] font-medium uppercase text-[#999]">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div>
    <div className="mt-2 grid grid-cols-7 gap-1.5">{cells.map((cell) => { const key = calendarDateKey(cell); const count = activity.get(key) || 0; const outside = cell.getMonth() !== cursor.getMonth(); const intensity = count >= 3 ? "bg-[#2F2F2F] text-white" : count === 2 ? "bg-[#80DC91] text-[#183C20]" : count === 1 ? "bg-[#CFF5D6] text-[#24552D]" : "bg-white text-[#9A9A9A]"; return <div key={cell.toISOString()} title={count ? `${count} session${count === 1 ? "" : "s"}` : "No sessions"} className={`relative grid aspect-square min-h-8 place-items-center rounded-[10px] text-[11px] transition ${intensity} ${outside ? "opacity-35" : ""} ${key === today ? "ring-1 ring-[#2F2F2F] ring-offset-1" : ""}`}>{cell.getDate()}{count > 1 ? <span className="absolute right-1 top-0.5 text-[7px] font-bold">{count}</span> : null}</div>; })}</div>
  </section>;
}

export default function ProfileProgressDashboard({ userId, timeZone }: { userId: string; timeZone: string }) {
  const [period, setPeriod] = useState<Period>("month");
  const [attendance, setAttendance] = useState<AttendanceRow[]>([]);
  const [dailyAttendance, setDailyAttendance] = useState<DailyAttendanceRow[]>([]);
  const [tasks, setTasks] = useState<CompletedTaskRow[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; setLoading(true); void Promise.all([
    supabase.from("session_attendance").select("session_id, joined_at, left_at, last_seen_at, created_at").eq("user_id", userId).order("joined_at", { ascending: false }).limit(1000),
    supabase.from("infinite_room_daily_attendance").select("session_id, attendance_date").eq("user_id", userId).order("attendance_date", { ascending: false }).limit(1500),
    supabase.from("focus_plan_items").select("id, text, target_date, created_at").eq("user_id", userId).eq("completed", true).order("created_at", { ascending: false }).limit(500),
    supabase.from("intentions").select("id, text, created_at").eq("user_id", userId).eq("completed", true).order("created_at", { ascending: false }).limit(500),
  ]).then(([attendanceResult, dailyResult, planResult, intentionsResult]) => { if (cancelled) return; setAttendance(attendanceResult.error ? [] : (attendanceResult.data as AttendanceRow[]) || []); setDailyAttendance(dailyResult.error ? [] : (dailyResult.data as DailyAttendanceRow[]) || []); const planRows = ((planResult.error ? [] : planResult.data) || []) as CompletedTaskRow[]; const intentionRows = ((intentionsResult.error ? [] : intentionsResult.data) || []) as CompletedTaskRow[]; const combined = [...planRows.map((row) => ({ ...row, id: `plan:${row.id}` })), ...intentionRows.map((row) => ({ ...row, id: `intention:${row.id}` }))]; setTasks(combined.sort((a, b) => new Date(b.created_at || 0).getTime() - new Date(a.created_at || 0).getTime())); }).catch((error) => { console.warn("[profile-progress] load failed", error); if (!cancelled) { setAttendance([]); setDailyAttendance([]); setTasks([]); } }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [userId]);
  const events = useMemo(() => { const result = new Map<string, ProgressEvent>(); attendance.forEach((row) => { const date = dateKey(row.joined_at || row.created_at, timeZone); if (!date || !row.session_id) return; const key = `${row.session_id}:${date}`; result.set(key, { key, date, minutes: getAttendanceMinutes(row) }); }); dailyAttendance.forEach((row) => { const date = dateKey(row.attendance_date, timeZone); const key = `${row.session_id}:${date}`; if (date && !result.has(key)) result.set(key, { key, date, minutes: 0 }); }); return Array.from(result.values()).sort((a, b) => b.date.localeCompare(a.date)); }, [attendance, dailyAttendance, timeZone]);
  const periodStats = useMemo(() => { const start = dateKey(addDays(new Date(), -(PERIOD_DAYS[period] - 1)), timeZone); const filteredEvents = events.filter((event) => event.date >= start); const filteredTasks = tasks.filter((task) => dateKey(task.target_date || task.created_at, timeZone) >= start); const activeDates = new Set(events.map((event) => event.date)); return { sessions: filteredEvents.length, minutes: filteredEvents.reduce((sum, event) => sum + event.minutes, 0), tasks: filteredTasks.length, streak: getStreak(activeDates, timeZone) }; }, [events, period, tasks, timeZone]);
  return <section id="profile-progress" className="mt-10 scroll-mt-24 overflow-hidden rounded-[28px] bg-white ring-1 ring-black/[0.08]"><header className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-7"><div><div className="flex items-center gap-2"><CalendarDays size={18} className="text-[#2F2F2F]" /><h2 className="text-[20px] font-bold text-[#2F2F2F]">Your progress</h2></div><p className="mt-1 text-[12px] text-[#777]">A visible record of focused time, completed tasks, and days you showed up.</p></div><div className="flex w-fit rounded-full bg-[#F1F1EF] p-1">{(["week", "month", "year"] as Period[]).map((item) => <button key={item} type="button" onClick={() => setPeriod(item)} className={`rounded-full px-4 py-2 text-[12px] font-semibold capitalize transition ${period === item ? "bg-[#2F2F2F] text-white" : "text-[#777] hover:text-[#2F2F2F]"}`}>{item}</button>)}</div></header>
    {loading ? <div className="grid min-h-72 place-items-center border-t border-black/[0.06]"><Loader2 className="animate-spin text-[#777]" size={24} /></div> : <><div className="grid grid-cols-2 gap-2 border-t border-black/[0.06] bg-[#FAFAF8] p-3 sm:grid-cols-4 sm:p-5">{[{ label: "Focused time", value: formatDuration(periodStats.minutes), icon: <Clock3 size={16} /> }, { label: "Sessions", value: periodStats.sessions, icon: <CalendarDays size={16} /> }, { label: "Tasks done", value: periodStats.tasks, icon: <Check size={16} /> }, { label: "Current streak", value: `${periodStats.streak}d`, icon: <Flame size={16} /> }].map((stat) => <div key={stat.label} className="rounded-[18px] bg-white p-4"><div className="flex items-center gap-2 text-[11px] font-medium text-[#858585]">{stat.icon}{stat.label}</div><div className="mt-3 text-[24px] font-bold leading-none text-[#2F2F2F]">{stat.value}</div></div>)}</div><div className="grid gap-4 p-4 sm:p-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(260px,.55fr)]"><Calendar events={events} timeZone={timeZone} /><section className="rounded-[22px] bg-[#F7F7F5] p-5"><div className="flex items-center justify-between"><h3 className="text-[15px] font-semibold text-[#2F2F2F]">Recently completed</h3><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-[#777]">{tasks.length} total</span></div><div className="mt-4 space-y-1.5">{tasks.length ? tasks.slice(0, 7).map((task) => <div key={task.id} className="flex items-start gap-3 rounded-[14px] bg-white px-3 py-3"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#D8F7DE] text-[#25843A]"><Check size={12} strokeWidth={3} /></span><div className="min-w-0"><p className="line-clamp-2 text-[12px] leading-5 text-[#3F3F3F]">{task.text || "Completed task"}</p><span className="mt-0.5 block text-[10px] text-[#A0A0A0]">{dateKey(task.target_date || task.created_at, timeZone)}</span></div></div>) : <div className="rounded-[16px] bg-white px-4 py-8 text-center text-[12px] leading-5 text-[#8C8C8C]">Completed tasks will appear here as you check them off.</div>}</div></section></div></>}
  </section>;
}
