-- User-controlled Web Push notifications for active public infinite rooms.
-- Missing preference rows are intentionally treated as enabled by application code.

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  browser_notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notification_preferences
  add column if not exists browser_notifications_enabled boolean not null default true,
  add column if not exists focus_presence_push_enabled boolean not null default true;

alter table public.notification_preferences
  alter column browser_notifications_enabled set default true,
  alter column focus_presence_push_enabled set default true;

alter table public.notification_preferences enable row level security;

drop policy if exists "Users can read their notification preferences"
  on public.notification_preferences;
create policy "Users can read their notification preferences"
  on public.notification_preferences
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create their notification preferences"
  on public.notification_preferences;
create policy "Users can create their notification preferences"
  on public.notification_preferences
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their notification preferences"
  on public.notification_preferences;
create policy "Users can update their notification preferences"
  on public.notification_preferences
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant select, insert, update on public.notification_preferences to authenticated;
grant all on public.notification_preferences to service_role;

create table if not exists public.push_presence_broadcasts (
  id bigint generated by default as identity primary key,
  room_session_id uuid not null references public.sessions(id) on delete cascade,
  participant_count integer not null check (participant_count > 0),
  subscriptions_count integer not null default 0 check (subscriptions_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  deleted_count integer not null default 0 check (deleted_count >= 0),
  sent_at timestamptz not null default now()
);

create index if not exists push_presence_broadcasts_room_sent_idx
  on public.push_presence_broadcasts (room_session_id, sent_at desc);

alter table public.push_presence_broadcasts enable row level security;
grant all on public.push_presence_broadcasts to service_role;
grant usage, select on sequence public.push_presence_broadcasts_id_seq to service_role;
