-- Discord announcements for public infinite rooms with active participants.

create table if not exists public.discord_presence_broadcasts (
  id bigint generated by default as identity primary key,
  room_session_id uuid not null references public.sessions(id) on delete cascade,
  participant_count integer not null check (participant_count > 0),
  message text not null,
  sent_at timestamptz not null default now()
);

create index if not exists discord_presence_broadcasts_room_sent_idx
  on public.discord_presence_broadcasts (room_session_id, sent_at desc);

alter table public.discord_presence_broadcasts enable row level security;

create or replace function public.get_active_infinite_rooms_for_discord(
  min_participants integer default 2,
  active_window_seconds integer default 90
)
returns table (
  session_id uuid,
  title text,
  participant_count bigint,
  is_private boolean
)
language sql
security definer
set search_path = public
stable
as $$
  select
    s.id as session_id,
    coalesce(nullif(trim(s.title), ''), 'Focus room') as title,
    count(distinct a.user_id) as participant_count,
    coalesce(s.is_private, false) as is_private
  from public.sessions s
  join public.session_attendance a on a.session_id = s.id
  where
    coalesce(s.is_private, false) = false
    and a.left_at is null
    and a.last_seen_at >= now() - make_interval(
      secs => greatest(30, least(coalesce(active_window_seconds, 90), 600))
    )
    and (
      lower(coalesce(s.session_format_type, '')) = 'infinite'
      or lower(coalesce(s.format, '')) = 'infinite'
      or coalesce(s.schedule ->> 'kind', '') = 'infinite_room'
      or jsonb_typeof(s.schedule -> 'timer' -> 'phases') = 'array'
      or jsonb_typeof(s.schedule -> 'phases') = 'array'
    )
  group by s.id, s.title, s.is_private
  having count(distinct a.user_id) >= greatest(1, least(coalesce(min_participants, 2), 100))
  order by participant_count desc, s.id;
$$;

revoke all on function public.get_active_infinite_rooms_for_discord(integer, integer)
  from public, anon, authenticated;
grant execute on function public.get_active_infinite_rooms_for_discord(integer, integer)
  to service_role;
